### PR TITLE
Fix compiler warnings when using -Wextra flag

### PR DESCRIPTION
**Pull request by dozack**
During compilation with `-pedantic` and `-Wextra` flags, a few warnings have occurred in HAL library. My fix neither does remove nor add any functionality, i have just void casted arguments unused in some situations (for example when `USE_FULL_ASSERT` is not enabled).

### CODE REVIEW

**Comment by RJMSTM** [comment]
Hello @dozack 

Thank you for your contribution. Would it be possible to share the project you have used to reproduce the warning in order to allow a better analysis of the problem.
How you add and set the flags **-pedanti** and **-Wextra** and which compiler  you use ?

- There is an open ticket on Bugzilla: 141354,  Can you confirm is that the same issue ?

Thanks.

With Regards, 
Rania.

**Comment by RJMSTM** [comment]
ST Internal Reference: 141354

**Comment by RJMSTM** [comment]
ST Internal Reference: 146680

**Comment by HBOSTM** [comment]
Hello @dozack 

The fix you requested has been implemented and is now available in the frame of the latest stm32l4_hal_driver package V1.18.0 release. This issue can be closed now. Thank you again for your contribution.

Best Regards,

**Pull request closed without merging**
